name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:base-devel
    steps:
      - name: Prepare
        run: |
          pacman-key --init
          pacman -Syu --noconfirm
          pacman -S --noconfirm git meson clang glslang libcap wlroots \
            sdl2 vulkan-headers libx11 libxmu libxcomposite libxrender libxres \
            libxtst libxkbcommon libdrm libinput wayland-protocols benchmark \
            xorg-xwayland pipewire cmake \
            libavif libheif aom rav1e libdecor libxdamage \
            luajit
            mkdir -p /usr/share/wayland-protocols/staging
            curl -L https://gitlab.freedesktop.org/wayland/wayland-protocols/-/raw/main/staging/xx-color-management/xx-color-management-v3.xml -o /usr/share/wayland-protocols/staging/xx-color-management-v3.xml
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build without OpenVR
        run: |
          meson setup build --prefix=/usr -Denable_openvr_support=false
          cd build
          ninja
